language: php

php:
  - hhvm
  - '7.3'
  - '7.4'
  - '8.0'
  - nightly

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi;'
